# Things to show:
# - Simple GET/POST form
# - Simple AJAX form
# - Getting variables from URL in routes and templates
from app import app
from flask import redirect, request, render_template, abort, jsonify


@app.route('/hello_world')
def hello_world():
    # This route simply returns the text "Hello World!"
    return 'Hello World!'


@app.route('/template_list_example')
def template_list_example():
    page_template = 'pages/template_list_example.jinja'

    # This list could've been generated by a database call.  I'm just
    # making a Python list of Python dictionaries for simplicity
    return_list = [
        {'name': 'Kvothe', 'role': 'Arcanist'},
        {'name': 'Elodin', 'role': 'Namer'},
        {'name': 'Manet', 'role': 'Apprentice'},
    ]

    return render_template(
        page_template,
        return_list=return_list
    )


@app.route('/simple_form', methods=['GET', 'POST'])
def simple_form():
    # This route accepts GET and POST HTTP requests'
    page_template = 'pages/simple_form.jinja'

    if request.method == 'GET':
        # If the user makes a GET request for /simple_form, we just
        # need to serve them the form
        return render_template(
            page_template,
        )
    elif request.method == 'POST':
        # If the user makes a POST request, we need to get the data
        # they submitted using our form and process that data

        # Check to see if the fields we're expecting are included
        # and valid
        text_input = request.form.get('text_input', None)
        select_input = request.form.get('select_input', None)

        if text_input is not None and select_input is not None:
            if int(select_input) == -1:
                # The user did not choose a valid option
                error_message = 'You must choose a valid value for Select Input'

                return render_template(
                    page_template,
                    error_message=error_message,
                )

            if text_input == '':
                # The user did not enter anything for text input
                error_message = 'You must enter a value for Text Input'

                return render_template(
                    page_template,
                    error_message=error_message,
                )
        else:
            # The user didn't enter either the text_input or select_input
            error_message = 'You must enter values for Text Input and Select Input'
            return render_template(
                page_template,
                error_message=error_message,
            )

        last_input = {
            'text_input': text_input,
            'select_input': select_input,
        }

        return render_template(
            page_template,
            last_input=last_input,
        )


@app.route('/ajax_example')
def ajax_example():
    page_template = 'pages/ajax_example.jinja'

    return render_template(
        page_template,
    )


@app.route('/ajax_add_item', methods=['POST'])
def ajax_add_item():
    user_input = request.get_json()

    user_input = user_input.upper()

    return jsonify({'new_item': user_input})


@app.route('/data_in_url/<url_data>')
def data_in_url(url_data):
    page_template = 'pages/data_in_url.jinja'

    # You could use url_data here as a Python variable
    url_data = url_data.lower()

    return render_template(
        page_template,
        url_data=url_data,
    )