# Things to show:
# - Simple GET/POST form
# - Simple AJAX form
# - Getting variables from URL in routes and templates
from app import app
from flask import redirect, request, render_template, abort, jsonify
from templates.pages.md5_hash import md5


@app.route('/')
def home():
    return 'So far this doesnt do anything'


@app.route('/md5_challenge')
def md5page():
    # This route Directs you to the page holding the md5 script"
    return render_template('pages/md5_challenge.jinja')


@app.route('/md5_challenge', methods=['POST'])
def md5_challenge():
    page_template = "pages/md5_challenge.jinja"

    if request.method == 'POST':
        # If the user makes a POST request, we need to get the data
        # they submitted using our form and process that data

        # Check to see if the fields we're expecting are included
        # and valid
        text_input = request.form.get('text_input', None)

        if text_input is None:
            # The user did not enter anything for text input
            error_message = 'You must enter a value for Text Input'

            return render_template(
                page_template,
                error_message=error_message,
            )
        else:
            md5result = md5(text_input)

            return render_template(
                page_template, md5result=md5result
            )


@app.route('/template_list_example')
def template_list_example():
    page_template = 'pages/template_list_example.jinja'

    # This list could've been generated by a database call.  I'm just
    # making a Python list of Python dictionaries for simplicity
    return_list = [
        {'name': 'Kvothe', 'role': 'Arcanist'},
        {'name': 'Elodin', 'role': 'Namer'},
        {'name': 'Manet', 'role': 'Apprentice'},
    ]

    return render_template(
        page_template,
        return_list=return_list
    )


@app.route('/ajax_example')
def ajax_example():
    page_template = 'pages/ajax_example.jinja'

    return render_template(
        page_template,
    )


@app.route('/ajax_add_item', methods=['POST'])
def ajax_add_item():
    user_input = request.get_json()

    user_input = user_input.upper()

    return jsonify({'new_item': user_input})


@app.route('/data_in_url/<url_data>')
def data_in_url(url_data):
    page_template = 'pages/data_in_url.jinja'

    # You could use url_data here as a Python variable
    url_data = url_data.lower()

    return render_template(
        page_template,
        url_data=url_data,
    )